### ISSUE TITLE
Rework station enclosure design

### ISSUE THREAD

**Issue by AxxAxx** [AxxAxx/AxxSolder#24]
Improvement of station enclosure to have a proper closed enclosure, good locations for screw threads where needed.

**Comment by f616** [comment]
Could you provide us with CAD files than can be edited in Fusion360?

**Comment by f616** [comment]
This is in what I'm working now.

![image](https://github.com/AxxAxx/AxxSolder/assets/3826426/24f77a3d-6939-4608-8d4f-f0fc0ac68211)

Wasn't yet printed and tested. If anyone finds value on this, and assuming the tests will be OK, please let me know and I can share the Fusion360 files.

**Comment by AxxAxx** [comment]
> Could you provide us with CAD files than can be edited in Fusion360?

The CAD designs was all made in SolidWorks. Therefore I do not have any Fusion compatible design files. The best I have for you to build on is .STEP, which are availible at  https://github.com/AxxAxx/AxxSolder/tree/main/CAD

**Comment by bennymeg** [comment]
It's also possible to import SolidWorks assemblies and parts directly into Fusion 360 now.

**Comment by AxxAxx** [comment]
fixed in AxxSolder 3.0
