### ISSUE TITLE
LCSC.com Part Numbers for v2.1 and v2.2

### ISSUE THREAD

**Issue by f616** [AxxAxx/AxxSolder#25]
Hi,

Those are the part numbers for v2.1 and v2.2 from [LCSC](https://lcsc.com)

| Part (v2.1)                                               | Part (v2.2)                                                         | LCSC.com/JLCPCB Part # | Footprint                            | Comment             |
| --------------------------------------------------------- | ------------------------------------------------------------------- | ---------------------- | ------------------------------------ | ------------------- |
| C1, C6, C12, C14, C19                                     | C1, C6, C12, C14, C19                                               | C15850                 | Capacitor_SMD:C_0805_2012Metric      | 10u                 |
| C2, C3, C5, C7, C8, C9, C10, C11, C13, C20, C21, C22, C24 | C2, C3, C5, C7, C8, C9, C10, C11, C13, C20, C21, C22, C24, C28, C29 | C49678                 | Capacitor_SMD:C_0805_2012Metric      | 100n                |
| C4, C17, C18                                              | C4, C25, C27                                                        | C12891                 | Capacitor_SMD:C_1206_3216Metric      | 22u                 |
| \--                                                       | C17, C18                                                            | C6119901               | Capacitor_SMD:C_0805_2012Metric      | 22u                 |
| C25                                                       | \--                                                                 | C45783                 | Capacitor_SMD:C_0805_2012Metric      | 22u                 |
| C15, C16                                                  | C15, C16                                                            | C46653                 | Capacitor_SMD:C_0805_2012Metric      | 1n                  |
| C23                                                       | C23                                                                 | C310841                | EMZR500ARA331MJA0G:CAPAE1030X1050N   | 330u                |
| C26                                                       | C26                                                                 | C113832                | Capacitor_SMD:C_0805_2012Metric      | 75p                 |
| D1, D3, D5, D6, D12                                       | D1, D3, D5, D6, D12                                                 | C916425                | BAT54S,215:SOT95P230X110-3N          | BAT54S              |
| D2                                                        | D2                                                                  | C2687553               | PMEG6020ER,115:PMEG6020ER115         | PMEG6020ER          |
| D4                                                        | D4                                                                  |                        |                                      |                     |
| D7                                                        | D7                                                                  | C503376                | PMEG10030ELPX:SODFL4725X110N         | PMEG10030ELPX       |
| D8                                                        | D8                                                                  | C707996                | SMCJ24CA:DIONM7969X262N              | SMCJ24CA            |
| F1                                                        | F1                                                                  | C352820                | 3557-2:3557-2                        | 10AFuse             |
| IC1                                                       | IC1                                                                 | C688540                | LTC4440AHMS8E-5#PBF:SOP65P490X110-9N | LTC4440AHMS8E-5#PBF |
| IC2                                                       | IC2                                                                 | C529357                | STM32G431KBT6:QFP80P900X900X160-32N  | STM32G431KBT6       |
| L1                                                        | L1                                                                  | C2847543               | INDPM7366X300N                       | SRP7028CC-100M      |
| IC3                                                       | IC3                                                                 | C2869735               | TMP236AQDBZRQ1:SOT95P237X112-3N      | TMP236AQDBZRQ1      |
| IC4                                                       | IC4                                                                 | C882727                | OPA2333AIDRBR:SON65P300X300X100-9N-D | OPA2333AIDRBR       |
| J1                                                        | J1                                                                  |                        |                                      |                     |
| J4                                                        | J4                                                                  |                        |                                      |                     |
| LS1                                                       | LS1                                                                 | C391032                | CMI-9653S-SMT-TR:CMI9653SSMTTR       | CMI-9653S-SMT-TR    |
| PS1                                                       | PS1                                                                 | C115288                | SOT230P700X190-4N                    | LD1117AS33TR        |
| IC6                                                       | IC6                                                                 | C311983                | SOT95P280X110-6N                     | TPS54302DDCR        |
| Q2                                                        | Q2                                                                  | C551416                | 2N7002NXAKR:SOT95P230X110-3N         | 2N7002NXAKR         |
| R1, R5, R6, R17, R25, R26                                 | R1, R5, R6, R17, R25, R26                                           | C17673                 | Resistor_SMD:R_0805_2012Metric       | 4k7                 |
| R2                                                        | R2                                                                  | C17713                 | Resistor_SMD:R_0805_2012Metric       | 47k                 |
| R3                                                        | R3                                                                  | C17772                 | Resistor_SMD:R_0805_2012Metric       | 6k8                 |
| R8, R9, R11, R12, R13, R14, R16, R18                      | R8, R9, R11, R12, R13, R14, R16, R18                                | C17414                 | Resistor_SMD:R_0805_2012Metric       | 10k                 |
| R10                                                       | R10                                                                 | C346458                | WSLP25122L500FEA:RESC6432X89N        | 2m                  |
| R15                                                       | R15                                                                 | C17557                 | Resistor_SMD:R_0805_2012Metric       | 220                 |
| R19, R20                                                  | R19, R20                                                            | C4310                  | Resistor_SMD:R_0805_2012Metric       | 1k5                 |
| R21, R22                                                  | R21, R22                                                            | C17709                 | Resistor_SMD:R_0805_2012Metric       | 470k                |
| R23, R24                                                  | R23, R24                                                            | C17556                 | Resistor_SMD:R_0805_2012Metric       | 220k                |
| R27                                                       | R27                                                                 | C17720                 | Resistor_SMD:R_0805_2012Metric       | 49.9                |
| R28                                                       | R28                                                                 | C149504                | Resistor_SMD:R_0805_2012Metric       | 100k                |
| R29                                                       | R29                                                                 | C17446                 | Resistor_SMD:R_0805_2012Metric       | 13k3                |
| U1                                                        | U1                                                                  |                        |                                      |                     |
| U2                                                        | U2                                                                  | C2760081               | BSC014N04LS:BSC014N04LS              | BSC014N04LS         |

I've orders the boards, but please bear in mind I've not tested them yet.

**update**
included the v2.2 components

**Comment by AxxAxx** [comment]
Thanks! 
This could be useful for people using LCSC.com/JLCPCB !

**Comment by Andy79881** [comment]
@f616 Thanks for your work regarding LCSC part numbers. I really appreciate that. Could you check for update to the latest HW release (V2.2)?

**Comment by f616** [comment]
@Andy79881 updated the table with the components from v2.2
I've a few pre-popuçated boards v2.1, If you need one, please let me know

**Comment by Andy79881** [comment]
@f616 Thanks for the update!
