### ISSUE TITLE
Remove unused ambient temperature sensor

### ISSUE THREAD

**Issue by AxxAxx** [AxxAxx/AxxSolder#3]
The ambient temperature sensor TMP236AQDBZRQ1 is unused and could be removed from PCB to reduce cost and complexity.
Firmware needs to be updated to not show ambient temperature anymore

**Comment by AxxAxx** [comment]
The temp sensor and capacitors are cheap (0.73 Euro), better leave it on PCB. It might come handy to have in the future.

**Comment by AxxAxx** [comment]
closed

**Comment by wfkbsse** [comment]
LTC4440A-5 is too expensive. Can you exchange it for a cheaper one

?
