### ISSUE TITLE
Settings item to limit output power

### ISSUE THREAD

**Issue by AxxAxx** [AxxAxx/AxxSolder#50]
Implement a setting where the user can limit the output power

e.g.

**Limit power**
0 - No limit except hard power limits specific for each cartridge type (NT115 - 20W, T210 - 60W, T245 - 120W)
10 - limit power to 10 W
20 - limit power to 20 W
...
110 - limit power to 110 W
120 - limit power to 120 W

**Comment by AxxAxx** [comment]
Implemneted with commit 
6d80659fd922b685760689f85c4cbb1505ae7119

**Comment by mrx23dot** [comment]
C210 manual says rated power 40W, is 50% overdrive still ok?

**Comment by AxxAxx** [comment]
I have tested all JBC tips running continuously at full power for a long time now and never had any issue. So I believe it is fine.
